services:
# Server pulls ports from .env file
  server:
    build:
      context: .
      args:
        SERVER_PORT: ${SERVER_PORT:-5050}
    ports:
      - "${SERVER_PORT:-5050}:${SERVER_PORT:-5050}"


